### PR TITLE
Add documentation for DigitalOcean volume resource.

### PR DESCRIPTION
**Pull request by andrewsomething**
@aybabtme

### CODE REVIEW

**Comment by nickvanw** [comment]
LGTM - can we get this in PR to terraform master as well?

**Comment by andrewsomething** [comment]
This isn't in terraform master yet. They wanted docs before merging it. That's why this is here :smile:

**Comment by nickvanw** [comment]
yeah! I was asking if we could open a PR into official terraform with this since it looks good :).

**Comment by aybabtme** [comment]
thanks @andrewsomething, I've cherry-picked your commit in https://github.com/digitalocean/terraform/commit/3169327ecb11b3d7c90b5089d91a06bc31e2eef9

**Pull request closed without merging**
